steps:
    - name: gcr.io/cloud-builders/docker
      args:
          - "-c"
          - >-
              docker pull
              $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:latest
              || exit 0
      id: Pull
      entrypoint: /bin/bash
    - name: gcr.io/cloud-builders/docker
      args:
          - build
          - "--cache-from"
          - >-
              $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:latest
          - "-t"
          - >-
              $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
          - "-t"
          - >-
              $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:latest
          - .
          - "-f"
          - Dockerfile
      id: Build
    - name: gcr.io/cloud-builders/docker
      args:
          - push
          - "--all-tags"
          - $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME
      id: Push
    - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
      args:
          - run
          - services
          - update
          - $_SERVICE_NAME
          - >-
              --image=$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
          - >-
              --update-labels=managed-by=gcp-cloud-build-deploy-cloud-run,gcb-trigger-id=$_TRIGGER_ID,gcb-trigger-region=$LOCATION,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID
          - "--region=$_DEPLOY_REGION"
          - "--quiet"
      id: Deploy
      entrypoint: gcloud
images:
    - >-
        $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
    - >-
        $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:latest
options:
    requestedVerifyOption: VERIFIED
    substitutionOption: ALLOW_LOOSE
    logging: CLOUD_LOGGING_ONLY
substitutions:
    REPO_NAME: marketingnutexhealth-dev-marketing-request-form
    _DEPLOY_REGION: europe-west1
    _AR_HOSTNAME: europe-west1-docker.pkg.dev
    _TRIGGER_ID: eb81dfe2-89a2-44f6-b6d7-a3bc7ac595fc
    _AR_REPOSITORY: cloud-run-source-deploy
    _AR_PROJECT_ID: nutexcorporate
    _SERVICE_NAME: marketing-request-form-git
tags:
    - gcp-cloud-build-deploy-cloud-run
    - marketing-request-form-git
